from decimal import Decimal


# Centralized UK tax-rate snapshots used by sync_tax_rates management command.
# Values are stored per tax-year start (2025 -> 2025/26).
TAX_RATE_SEED_DATA = {
    2024: {
        "personal_allowance": Decimal("12570.00"),
        "blind_allowance": Decimal("3070.00"),
        "mca_relief_amount": Decimal("1108.00"),
        "personal_allowance_taper_threshold": Decimal("100000.00"),
        "basic_rate": Decimal("20.00"),
        "higher_rate": Decimal("40.00"),
        "additional_rate": Decimal("45.00"),
        "basic_threshold": Decimal("37700.00"),
        "higher_threshold": Decimal("125140.00"),
        "ni_threshold": Decimal("12570.00"),
        "ni_rate": Decimal("8.00"),
        "ni_additional_rate": Decimal("2.00"),
        "ni_upper_limit": Decimal("50270.00"),
        "starter_rate_scotland": Decimal("0.19"),
        "basic_rate_scotland": Decimal("0.20"),
        "intermediate_rate_scotland": Decimal("0.21"),
        "higher_rate_scotland": Decimal("0.42"),
        "advanced_rate_scotland": Decimal("0.45"),
        "top_rate_scotland": Decimal("0.48"),
        "starter_threshold_scotland": Decimal("2306.00"),
        "basic_threshold_scotland": Decimal("13991.00"),
        "intermediate_threshold_scotland": Decimal("31092.00"),
        "higher_threshold_scotland": Decimal("62430.00"),
        "advanced_threshold_scotland": Decimal("112570.00"),
    },
    2025: {
        "personal_allowance": Decimal("12570.00"),
        "blind_allowance": Decimal("3130.00"),
        "mca_relief_amount": Decimal("1137.00"),
        "personal_allowance_taper_threshold": Decimal("100000.00"),
        "basic_rate": Decimal("20.00"),
        "higher_rate": Decimal("40.00"),
        "additional_rate": Decimal("45.00"),
        "basic_threshold": Decimal("37700.00"),
        "higher_threshold": Decimal("125140.00"),
        "ni_threshold": Decimal("12570.00"),
        "ni_rate": Decimal("8.00"),
        "ni_additional_rate": Decimal("2.00"),
        "ni_upper_limit": Decimal("50270.00"),
        "starter_rate_scotland": Decimal("0.19"),
        "basic_rate_scotland": Decimal("0.20"),
        "intermediate_rate_scotland": Decimal("0.21"),
        "higher_rate_scotland": Decimal("0.42"),
        "advanced_rate_scotland": Decimal("0.45"),
        "top_rate_scotland": Decimal("0.48"),
        "starter_threshold_scotland": Decimal("2827.00"),
        "basic_threshold_scotland": Decimal("14921.00"),
        "intermediate_threshold_scotland": Decimal("31092.00"),
        "higher_threshold_scotland": Decimal("62430.00"),
        "advanced_threshold_scotland": Decimal("112570.00"),
    },
    2026: {
        "personal_allowance": Decimal("12570.00"),
        "blind_allowance": Decimal("3250.00"),
        "mca_relief_amount": Decimal("1170.00"),
        "personal_allowance_taper_threshold": Decimal("100000.00"),
        "basic_rate": Decimal("20.00"),
        "higher_rate": Decimal("40.00"),
        "additional_rate": Decimal("45.00"),
        "basic_threshold": Decimal("37700.00"),
        "higher_threshold": Decimal("125140.00"),
        "ni_threshold": Decimal("12570.00"),
        "ni_rate": Decimal("8.00"),
        "ni_additional_rate": Decimal("2.00"),
        "ni_upper_limit": Decimal("50270.00"),
        "starter_rate_scotland": Decimal("0.19"),
        "basic_rate_scotland": Decimal("0.20"),
        "intermediate_rate_scotland": Decimal("0.21"),
        "higher_rate_scotland": Decimal("0.42"),
        "advanced_rate_scotland": Decimal("0.45"),
        "top_rate_scotland": Decimal("0.48"),
        "starter_threshold_scotland": Decimal("3967.00"),
        "basic_threshold_scotland": Decimal("16956.00"),
        "intermediate_threshold_scotland": Decimal("31092.00"),
        "higher_threshold_scotland": Decimal("62430.00"),
        "advanced_threshold_scotland": Decimal("125140.00"),
    },
}


# Maintainer references for updates/verification.
TAX_RATE_SOURCES = {
    "rUK_income_tax": "https://www.gov.uk/income-tax-rates",
    "scotland_income_tax": "https://www.gov.scot/publications/scottish-income-tax-rates-and-bands/",
    "ni_rates_thresholds": "https://www.gov.uk/national-insurance-rates-letters",
    "blind_person_allowance": "https://www.gov.uk/blind-persons-allowance",
    "married_couples_allowance": "https://www.gov.uk/married-couples-allowance",
}
