# Generated by Django 5.0.6 on 2024-07-09 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('personal_allowance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('basic_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('higher_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('additional_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ni_threshold', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ni_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ni_additional_rate', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
