# Generated by Django 5.0.6 on 2024-07-09 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxrate',
            name='location',
            field=models.CharField(default='ENG', max_length=50),
        ),
    ]
