# Generated by Django 5.0.6 on 2024-07-09 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_taxrate_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxrate',
            name='basic_rate_scotland',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='taxrate',
            name='higher_rate_scotland',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='taxrate',
            name='intermediate_rate_scotland',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='taxrate',
            name='top_rate_scotland',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
