# Generated by Django 5.0.6 on 2024-07-09 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_taxrate_basic_rate_scotland_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxrate',
            name='additional_rate_scotland',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
