# Generated by Django 5.0.6 on 2024-07-09 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0004_taxrate_additional_rate_scotland'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxrate',
            name='additional_rate_scotland',
        ),
        migrations.RemoveField(
            model_name='taxrate',
            name='location',
        ),
        migrations.AddField(
            model_name='taxrate',
            name='starter_rate_scotland',
            field=models.DecimalField(decimal_places=2, default=0.19, max_digits=5),
        ),
        migrations.AlterField(
            model_name='taxrate',
            name='basic_rate_scotland',
            field=models.DecimalField(decimal_places=2, default=0.2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='taxrate',
            name='higher_rate_scotland',
            field=models.DecimalField(decimal_places=2, default=0.42, max_digits=5),
        ),
        migrations.AlterField(
            model_name='taxrate',
            name='intermediate_rate_scotland',
            field=models.DecimalField(decimal_places=2, default=0.21, max_digits=5),
        ),
        migrations.AlterField(
            model_name='taxrate',
            name='top_rate_scotland',
            field=models.DecimalField(decimal_places=2, default=0.45, max_digits=5),
        ),
    ]
