# Generated by Django 5.0.6 on 2024-07-09 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0005_remove_taxrate_additional_rate_scotland_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxrate',
            name='basic_rate_scotland',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='taxrate',
            name='higher_rate_scotland',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='taxrate',
            name='intermediate_rate_scotland',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='taxrate',
            name='starter_rate_scotland',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='taxrate',
            name='top_rate_scotland',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
