# Generated by Django 5.0.6 on 2025-02-03 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0006_alter_taxrate_basic_rate_scotland_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxrate',
            name='basic_threshold',
            field=models.DecimalField(decimal_places=2, default=37700, max_digits=10),
        ),
        migrations.AddField(
            model_name='taxrate',
            name='basic_threshold_scotland',
            field=models.DecimalField(decimal_places=2, default=13991, max_digits=10),
        ),
        migrations.AddField(
            model_name='taxrate',
            name='higher_threshold',
            field=models.DecimalField(decimal_places=2, default=125140, max_digits=10),
        ),
        migrations.AddField(
            model_name='taxrate',
            name='higher_threshold_scotland',
            field=models.DecimalField(decimal_places=2, default=125140, max_digits=10),
        ),
        migrations.AddField(
            model_name='taxrate',
            name='intermediate_threshold_scotland',
            field=models.DecimalField(decimal_places=2, default=31092, max_digits=10),
        ),
        migrations.AddField(
            model_name='taxrate',
            name='ni_upper_limit',
            field=models.DecimalField(decimal_places=2, default=50000, max_digits=10),
        ),
        migrations.AddField(
            model_name='taxrate',
            name='personal_allowance_taper_threshold',
            field=models.DecimalField(decimal_places=2, default=100000, max_digits=10),
        ),
        migrations.AddField(
            model_name='taxrate',
            name='starter_threshold_scotland',
            field=models.DecimalField(decimal_places=2, default=2306, max_digits=10),
        ),
    ]
