# Generated by Django 5.0.6 on 2026-02-25 11:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calculator", "0007_taxrate_basic_threshold_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="taxrate",
            name="advanced_rate_scotland",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="taxrate",
            name="advanced_threshold_scotland",
            field=models.DecimalField(decimal_places=2, default=125140, max_digits=10),
        ),
        migrations.AddField(
            model_name="taxrate",
            name="blind_allowance",
            field=models.DecimalField(decimal_places=2, default=3130, max_digits=10),
        ),
        migrations.AddField(
            model_name="taxrate",
            name="mca_relief_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="taxrate",
            name="higher_threshold_scotland",
            field=models.DecimalField(decimal_places=2, default=62430, max_digits=10),
        ),
    ]
