# Generated by Django 5.0.6 on 2026-02-26 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0010_fix_scotland_advanced_thresholds"),
    ]

    operations = [
        migrations.CreateModel(
            name="UsageEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("page_view", "Page View"),
                            ("calculate_submit", "Calculator Submit"),
                            ("api_call", "API Call"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("path", models.CharField(db_index=True, max_length=255)),
                ("method", models.CharField(max_length=8)),
                ("status_code", models.PositiveSmallIntegerField()),
                ("client_hash", models.CharField(blank=True, db_index=True, max_length=64)),
                ("user_agent", models.CharField(blank=True, max_length=255)),
                ("tax_year", models.IntegerField(blank=True, db_index=True, null=True)),
                ("income_type", models.CharField(blank=True, db_index=True, max_length=16)),
                (
                    "workweek_hours",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
                ),
                ("is_scotland", models.BooleanField(blank=True, null=True)),
                ("is_blind", models.BooleanField(blank=True, null=True)),
                ("no_ni", models.BooleanField(blank=True, null=True)),
                ("mca", models.BooleanField(blank=True, null=True)),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
    ]
