# Generated by Django 5.0.6 on 2026-02-26 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0011_usageevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="usageevent",
            name="client_ip",
            field=models.CharField(blank=True, db_index=True, max_length=45),
        ),
    ]
