# Generated by Django 5.0.6 on 2026-02-26 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0012_usageevent_client_ip"),
    ]

    operations = [
        migrations.AddField(
            model_name="usageevent",
            name="income",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
