# Generated by Django 5.0.6 on 2026-02-26 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0013_usageevent_income"),
    ]

    operations = [
        migrations.AddField(
            model_name="usageevent",
            name="client_kind",
            field=models.CharField(blank=True, db_index=True, max_length=16),
        ),
        migrations.AddField(
            model_name="usageevent",
            name="is_bot",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
